name: 'StyLua'
description: 'GitHub Action to run StyLua, an opinionated Lua code formatter'
author: 'JohnnyMorganz'
branding:
  icon: code
  color: orange
inputs:
  token:
    description: 'The GITHUB_SECRET token'
    required: true
  version:
    description: 'The version of StyLua to run. Use `latest` to pull the latest version'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
